//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockawayWish.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public int EventId { get; set; }
        public int EventLocationId { get; set; }
        public System.DateTime EventDateTime { get; set; }
        public string EventDescription { get; set; }
        public System.DateTime create_dt { get; set; }
    
        public virtual EventLocations EventLocation { get; set; }
    }
}
