//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockawayWish.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentType
    {
        public PaymentType()
        {
            this.UsersDues = new HashSet<UsersDue>();
        }
    
        public int PaymentTypeId { get; set; }
        public string PaymentTypeName { get; set; }
        public System.DateTime create_dt { get; set; }
    
        public virtual ICollection<UsersDue> UsersDues { get; set; }
    }
}
