//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockawayWish.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RockawayWishDBContext : DbContext
    {
        public RockawayWishDBContext()
            : base("name=RockawayWishDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<AspNetRole> AspNetRoles { get; set; }
        public DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public DbSet<AspNetUser> AspNetUsers { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<ContactUs> ContactUs1 { get; set; }
        public DbSet<Dues> Dues1 { get; set; }
        public DbSet<EventLocations> EventLocations1 { get; set; }
        public DbSet<Events> Events1 { get; set; }
        public DbSet<PaymentType> PaymentTypes { get; set; }
        public DbSet<States> States1 { get; set; }
        public DbSet<UsersDue> UsersDues { get; set; }
        public DbSet<PaymentTypes> PaymentTypes1 { get; set; }
    }
}
