//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockawayWish.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RockawayWishDBContainer : DbContext
    {
        public RockawayWishDBContainer()
            : base("name=RockawayWishDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ContactUs> ContactUs { get; set; }
        public DbSet<Dues> Dues { get; set; }
        public DbSet<EventLocations> EventLocations { get; set; }
        public DbSet<Events> Events { get; set; }
        public DbSet<PaymentTypes> PaymentTypes { get; set; }
        public DbSet<States> States { get; set; }
        public DbSet<UsersDues> UsersDues { get; set; }
    }
}
