//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockawayWish.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class States
    {
        public States()
        {
            this.ContactUs = new HashSet<ContactUs>();
            this.EventLocations = new HashSet<EventLocations>();
        }
    
        public int StateId { get; set; }
        public string StateName { get; set; }
        public string StateAbbr { get; set; }
        public System.DateTime create_dt { get; set; }
    
        public virtual ICollection<ContactUs> ContactUs { get; set; }
        public virtual ICollection<EventLocations> EventLocations { get; set; }
    }
}
