//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockawayWish.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersDue
    {
        public int UsersDuesId { get; set; }
        public System.Guid Id { get; set; }
        public int DuesId { get; set; }
        public int PaymentTypeId { get; set; }
        public System.DateTime DuesPaidDate { get; set; }
        public System.DateTime create_dt { get; set; }
    
        public virtual Due Due { get; set; }
        public virtual PaymentType PaymentType { get; set; }
    }
}
